// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------------- //
// direction_pulse //
// --------------- //

#define direction_pulse_wrap_target 0
#define direction_pulse_wrap 3

static const uint16_t direction_pulse_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block                      
    0xbf42, //  1: nop                           [31]
    0x6001, //  2: out    pins, 1                    
    0x0000, //  3: jmp    0                          
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program direction_pulse_program = {
    .instructions = direction_pulse_program_instructions,
    .length = 4,
    .origin = -1,
};

static inline pio_sm_config direction_pulse_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + direction_pulse_wrap_target, offset + direction_pulse_wrap);
    return c;
}
#endif
