// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------- //
// direction_irq //
// ------------- //

#define direction_irq_wrap_target 0
#define direction_irq_wrap 6

static const uint16_t direction_irq_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block                      
    0x605e, //  1: out    y, 30                      
    0xb242, //  2: nop                           [18]
    0x6001, //  3: out    pins, 1                    
    0x0084, //  4: jmp    y--, 4                     
    0xc000, //  5: irq    nowait 0                   
    0x0000, //  6: jmp    0                          
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program direction_irq_program = {
    .instructions = direction_irq_program_instructions,
    .length = 7,
    .origin = -1,
};

static inline pio_sm_config direction_irq_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + direction_irq_wrap_target, offset + direction_irq_wrap);
    return c;
}
#endif
