#pragma once

enum GameState
{
    CALIBRATION,
    STAND_BY,
    MATCH_INIT,
    MATCH_INIT_PROGRESS,
    MATCH_INIT_DONE,
    MATCH_SERVE,
    MATCH_SERVE_PROGRESS,
    MATCH_RUN,
    MATCH_END,
    SERVE_PROGRESS,
    BOUNCE_PROGRESS,
    HIT_PROGRESS,
    CENTER,
    CENTER_PROGRESS,
    CENTER_STANDBY,
    CENTER_STANDBY_PROGRESS
};